# 4 个空格
tabWidth: 4
# 结尾添加 ; 分号
semi: true
# 表达式左右添加空格 { x : a }
bracketSpacing: true
# jsx 元素结尾 > 在下一行，不贴着最后一个属性
bracketSameLine: false
# 不使用制表符
useTabs: false
# lambda 表达式使用 () 包裹
arrowParens: always
# https://prettier.nodejs.cn/docs/en/options.html
